=== youziliang/freeswitch-dynamic-loader/dal/dalgen/config/table-config-1.0.dtd
<?xml version="1.0" encoding="UTF-8" ?>
        <!--
        table 下包含多个 column resultmap operation sql 相应说明见定义
        namespace    命名空间
        sqlname      sql名
        remark      说明
        sequence     oracle使用
        physicalName 物理表名,分库分表使用
        -->
        <!ELEMENT table (column* | resultmap* | operation*)+>
        <!ATTLIST table
                sqlname CDATA #IMPLIED
                sequence CDATA #IMPLIED
                physicalName CDATA #IMPLIED
                remark CDATA #IMPLIED
                >
        <!--
        column 字段定义,定义字段对应javatype
        name          数据中字段名
        javatype      对应转为那种javaType
        relatedColumn 针对 com.alipay.fc.common.lang.money.MultiCurrencyMoney 扩展
        -->
        <!ELEMENT column EMPTY>
        <!ATTLIST column
                name CDATA #REQUIRED
                javatype CDATA #REQUIRED
                jdbctype CDATA #REQUIRED
                remark CDATA #REQUIRED
                relatedColumn CDATA #IMPLIED
                >

        <!--
         自定义resultMap 会生成 customer/${type}.java
         name        提供给operation 使用
         type        自定义映射名
         -->
        <!ELEMENT resultmap (column)*>
        <!ATTLIST resultmap
                name CDATA #REQUIRED
                type CDATA #REQUIRED
                remark CDATA #IMPLIED
                >
        <!--
        最定义操作, 根据这里生成对应的 操作
        name          name
        paging        分页设置  - 暂时没想好怎么扩展 -后续加上(思路,如果设置paging 则自动添加分页参数 不需要自己写limit 只需要写查询条件即可)
        paramtype     参数类型: object 会自动翻译为 生成的对象,primitive 根据字段类型生成
        multiplicity  one 返回对象,many 返回list, paging 返回分页
        resulttype    指定返回类型(Map)
        resultmap     指定使用哪个resultmap 不写则使用自动生成的resultMap
        timeout       设置超时时间
        auto           - 暂时没想好怎么用,设想新增字段时自动修复
        -->
        <!ELEMENT operation (extra-param|sqlmap)*>
        <!ATTLIST operation
                name CDATA #REQUIRED
                paging CDATA #IMPLIED
                paramtype (object|primitive) #IMPLIED
                multiplicity (one|many|paging) #IMPLIED
                remark CDATA #IMPLIED
                resulttype CDATA #IMPLIED
                resultmap CDATA #IMPLIED
                timeout CDATA #IMPLIED
                >

        <!ELEMENT extra-param (param)+>
        <!ELEMENT param EMPTY>
        <!ATTLIST param
                name CDATA #REQUIRED
                javatype CDATA #REQUIRED
                remark CDATA #IMPLIED
                >

        <!ELEMENT sqlmap (#PCDATA | selectKey | include | trim | where | set | foreach | choose | if | bind)*>



        <!ELEMENT include EMPTY>
        <!ATTLIST include
                refid CDATA #REQUIRED
                >


        <!ELEMENT selectKey (#PCDATA | include)*>
        <!ATTLIST selectKey
                resultType CDATA #IMPLIED
                keyProperty CDATA #IMPLIED
                order (BEFORE|AFTER) #IMPLIED
                >

        <!-- - - - - - - - - - - - - - - - - - - - - - - - -
                         DYNAMIC ELEMENTS
          - - - - - - - - - - - - - - - - - - - - - - - - -->


        <!ELEMENT bind EMPTY>
        <!ATTLIST bind
                name CDATA #REQUIRED
                value CDATA #REQUIRED
                >

        <!ELEMENT trim (#PCDATA | include | trim | where | set | foreach | choose | if | bind)*>
        <!ATTLIST trim
                prefix CDATA #IMPLIED
                prefixOverrides CDATA #IMPLIED
                suffix CDATA #IMPLIED
                suffixOverrides CDATA #IMPLIED
                >
        <!ELEMENT where (#PCDATA | include | trim | where | set | foreach | choose | if | bind)*>
        <!ELEMENT set (#PCDATA | include | trim | where | set | foreach | choose | if | bind)*>

        <!ELEMENT foreach (#PCDATA | include | trim | where | set | foreach | choose | if | bind)*>
        <!ATTLIST foreach
                collection CDATA #REQUIRED
                item CDATA #IMPLIED
                index CDATA #IMPLIED
                open CDATA #IMPLIED
                close CDATA #IMPLIED
                separator CDATA #IMPLIED
                >

        <!ELEMENT choose (when* , otherwise?)>
        <!ELEMENT when (#PCDATA | include | trim | where | set | foreach | choose | if | bind)*>
        <!ATTLIST when
                test CDATA #REQUIRED
                >
        <!ELEMENT otherwise (#PCDATA | include | trim | where | set | foreach | choose | if | bind)*>

        <!ELEMENT if (#PCDATA | include | trim | where | set | foreach | choose | if | bind)*>
        <!ATTLIST if
                test CDATA #REQUIRED
                >

=== youziliang/freeswitch-dynamic-loader/dal/dalgen/dev_cl_smsTables/ag_batch_record.xml
<!DOCTYPE table SYSTEM "../config/table-config-1.0.dtd">
<table sqlname="ag_batch_record" physicalName="ag_batch_record" remark="ag_batch_record">
    <!--  特殊字符说明  &lt;&gt;   <> -->

    <operation name="insert" paramtype="object" remark="插入表:ag_batch_record">
        <sqlmap>
            <selectKey resultType="java.lang.Long" keyProperty="id" order="AFTER">
                SELECT
                LAST_INSERT_ID()
            </selectKey>
            insert into ag_batch_record
            <trim prefix="(" suffix=")" suffixOverrides=",">
                <if test="id != null">
                    id,
                </if>
                <if test="batchNo != null">
                    batch_no,
                </if>
                <if test="receTel != null">
                    rece_tel,
                </if>
                <if test="ifRepeat != null">
                    if_repeat,
                </if>
                <if test="ifCorrect != null">
                    if_correct,
                </if>
                <if test="vars != null">
                    vars,
                </if>
                <if test="createTime != null">
                    create_time,
                </if>
                <if test="updateTime != null">
                    update_time,
                </if>
            </trim>
            <trim prefix="values (" suffix=")" suffixOverrides=",">
                <if test="id != null">
                    #{id,jdbcType=BIGINT},
                </if>
                <if test="batchNo != null">
                    #{batchNo,jdbcType=VARCHAR},
                </if>
                <if test="receTel != null">
                    #{receTel,jdbcType=VARCHAR},
                </if>
                <if test="ifRepeat != null">
                    #{ifRepeat,jdbcType=BIT},
                </if>
                <if test="ifCorrect != null">
                    #{ifCorrect,jdbcType=BIT},
                </if>
                <if test="vars != null">
                    #{vars,jdbcType=VARCHAR},
                </if>
                <if test="createTime != null">
                    #{createTime,jdbcType=INTEGER},
                </if>
                <if test="updateTime != null">
                    #{updateTime,jdbcType=INTEGER},
                </if>
            </trim>
        </sqlmap>
    </operation>

    <operation name="update" paramtype="object" remark="更新表:ag_batch_record">
        <sqlmap>
            UPDATE ag_batch_record
            SET
            <trim suffixOverrides=",">
                <if test="batchNo != null">
                    batch_no = #{batchNo,jdbcType=VARCHAR},
                </if>
                <if test="receTel != null">
                    rece_tel = #{receTel,jdbcType=VARCHAR},
                </if>
                <if test="ifRepeat != null">
                    if_repeat = #{ifRepeat,jdbcType=BIT},
                </if>
                <if test="ifCorrect != null">
                    if_correct = #{ifCorrect,jdbcType=BIT},
                </if>
                <if test="vars != null">
                    vars = #{vars,jdbcType=VARCHAR},
                </if>
                <if test="createTime != null">
                    create_time = #{createTime,jdbcType=INTEGER},
                </if>
                <if test="updateTime != null">
                    update_time = #{updateTime,jdbcType=INTEGER},
                </if>
            </trim>
            WHERE
            id = #{id,jdbcType=BIGINT}
        </sqlmap>
    </operation>

    <operation name="deleteByPrimary" multiplicity="one" remark="根据主键删除数据:ag_batch_record">
        <sqlmap>
            DELETE FROM
            ag_batch_record
            WHERE
            id = #{id,jdbcType=BIGINT}
        </sqlmap>
    </operation>

    <operation name="getByPrimary" multiplicity="one" remark="根据主键获取数据:ag_batch_record">
        <sqlmap>
            SELECT *
            FROM ag_batch_record
            WHERE
            id = #{id,jdbcType=BIGINT}
        </sqlmap>
    </operation>

    <operation name="insertTelsOrVars" multiplicity="many" remark="批量插入手机号或变量:ag_batch_record">
        <sqlmap>
            <foreach collection="list" item="object" index="index" separator=";">
                insert into ag_batch_record
                <trim prefix="(" suffix=")" suffixOverrides=",">
                    <if test="object.id != null">
                        id,
                    </if>
                    <if test="object.batchNo != null">
                        batch_no,
                    </if>
                    <if test="object.receTel != null">
                        rece_tel,
                    </if>
                    <if test="object.ifRepeat != null">
                        if_repeat,
                    </if>
                    <if test="object.ifCorrect != null">
                        if_correct,
                    </if>
                    <if test="object.vars != null">
                        vars,
                    </if>
                    <if test="object.createTime != null">
                        create_time,
                    </if>
                    <if test="object.updateTime != null">
                        update_time,
                    </if>
                </trim>
                <trim prefix="values (" suffix=")" suffixOverrides=",">
                    <if test="object.id != null">
                        #{object.id,jdbcType=BIGINT},
                    </if>
                    <if test="object.batchNo != null">
                        #{object.batchNo,jdbcType=VARCHAR},
                    </if>
                    <if test="object.receTel != null">
                        #{object.receTel,jdbcType=VARCHAR},
                    </if>
                    <if test="object.ifRepeat != null">
                        #{object.ifRepeat,jdbcType=BIT},
                    </if>
                    <if test="object.ifCorrect != null">
                        #{object.ifCorrect,jdbcType=BIT},
                    </if>
                    <if test="object.vars != null">
                        #{object.vars,jdbcType=VARCHAR},
                    </if>
                    <if test="object.createTime != null">
                        #{object.createTime,jdbcType=INTEGER},
                    </if>
                    <if test="object.updateTime != null">
                        #{object.updateTime,jdbcType=INTEGER},
                    </if>
                </trim>
            </foreach>
        </sqlmap>
    </operation>
</table>
